# -*- coding: utf-8 -*-
"""analisis_ventas_Github.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJFUV2vSKCzo1ysp_weyrgX6HfLNf68b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

# Config para gráficas bonitas
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

# 1. SIMULACIÓN DE DATOS - ETL
np.random.seed(42)
num_ventas = 1000

# Generar datos realistas
fechas = [datetime(2024, 1, 1) + timedelta(days=np.random.randint(0, 365)) for _ in range(num_ventas)]
productos = np.random.choice(['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Webcam'], num_ventas, p=[0.15, 0.3, 0.2, 0.2, 0.15])
regiones = np.random.choice(['Norte', 'Sur', 'Centro', 'Occidente'], num_ventas)
vendedores = np.random.choice(['Ana', 'Luis', 'Maria', 'Carlos', 'Sofia'], num_ventas)

precios = {'Laptop': 15000, 'Mouse': 500, 'Teclado': 1200, 'Monitor': 4500, 'Webcam': 800}
precio_unit = [precios[p] for p in productos]
cantidad = np.random.randint(1, 5, num_ventas)
descuento = np.random.choice([0, 0.05, 0.1, 0.15], num_ventas, p=[0.5, 0.2, 0.2, 0.1])

df = pd.DataFrame({
    'fecha': fechas,
    'producto': productos,
    'region': regiones,
    'vendedor': vendedores,
    'precio_unitario': precio_unit,
    'cantidad': cantidad,
    'descuento': descuento
})

# 2. TRANSFORMACIÓN - Feature Engineering
df['ingreso_bruto'] = df['precio_unitario'] * df['cantidad']
df['ingreso_neto'] = df['ingreso_bruto'] * (1 - df['descuento'])
df['mes'] = df['fecha'].dt.to_period('M')
df['trimestre'] = df['fecha'].dt.quarter

# 3. ANÁLISIS - KPIs DE NEGOCIO
print("=== KPIs GENERALES ===")
print(f"Ingreso Total: ${df['ingreso_neto'].sum():,.2f}")
print(f"Ticket Promedio: ${df['ingreso_neto'].mean():,.2f}")
print(f"Unidades Vendidas: {df['cantidad'].sum():,}")
print(f"Descuento Promedio: {df['descuento'].mean():.1%}")

# 4. AGREGACIONES CLAVE
ventas_mes = df.groupby('mes')['ingreso_neto'].sum().reset_index()
ventas_producto = df.groupby('producto').agg({
    'ingreso_neto': 'sum',
    'cantidad': 'sum'
}).sort_values('ingreso_neto', ascending=False).reset_index()

ventas_vendedor = df.groupby('vendedor')['ingreso_neto'].sum().sort_values(ascending=False)
ventas_region = df.groupby('region')['ingreso_neto'].sum().sort_values(ascending=False)

# 5. INSIGHTS
print("\n=== TOP PRODUCTOS POR INGRESO ===")
print(ventas_producto)

print("\n=== TOP VENDEDORES ===")
print(ventas_vendedor)

# 6. VISUALIZACIONES - Dashboard Ejecutivo
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Dashboard Ejecutivo de Ventas 2024', fontsize=16, weight='bold')

# Graf 1: Ventas por mes
ventas_mes['mes'] = ventas_mes['mes'].astype(str)
sns.lineplot(data=ventas_mes, x='mes', y='ingreso_neto', marker='o', ax=axes[0,0])
axes[0,0].set_title('Tendencia Mensual de Ingresos')
axes[0,0].set_ylabel('Ingreso Neto MXN')
axes[0,0].tick_params(axis='x', rotation=45)

# Graf 2: Ventas por producto
sns.barplot(data=ventas_producto, x='ingreso_neto', y='producto', ax=axes[0,1], palette='viridis')
axes[0,1].set_title('Ingreso por Producto')
axes[0,1].set_xlabel('Ingreso Neto MXN')

# Graf 3: Ventas por vendedor
ventas_vendedor.plot(kind='bar', ax=axes[1,0], color='coral')
axes[1,0].set_title('Performance por Vendedor')
axes[1,0].set_ylabel('Ingreso Neto MXN')
axes[1,0].tick_params(axis='x', rotation=0)

# Graf 4: Ventas por región
ventas_region.plot(kind='pie', ax=axes[1,1], autopct='%1.1f%%', startangle=90)
axes[1,1].set_title('Distribucion de Ventas por Region')
axes[1,1].set_ylabel('')

plt.tight_layout()
plt.savefig('dashboard_ventas.png', dpi=300, bbox_inches='tight')
print("\nDashboard guardado: dashboard_ventas.png")

# 7. EXPORTAR RESULTADOS
ventas_mes.to_csv('ventas_mensuales.csv', index=False)
ventas_producto.to_csv('ventas_por_producto.csv', index=False)
print("CSVs exportados para BI")